version: "3.7"
services: 
    server:
        build:
            dockerfile: Dockerfile
            context: .
        networks:
            - backend
        ports:
            - "10000:80"
        environment:
            pgHost: "database"
            pgPort: 5432
            pgUser: "postgres"
            pgPassword: "postgres_docker"
            pgDbName: "annonces"      
            dbType: "POSTGRES" 
        depends_on:
            - database   
        links:
            - database
    database:
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: "postgres_docker"
            POSTGRES_DB: "annonces"
            POSTGRES_USER: "postgres"
            POSTGRES_HOST: "0.0.0.0"
            POSTGRES_PORT: 5432
            PGDATA: /var/lib/postgresql/data/pg_data
        ports:
            - "9000:5432"
        volumes: 
            - data:/var/lib/postgresql/data
        networks:
            - backend
volumes:
    data:
networks:
    backend:
        driver: bridge